### ISSUE TITLE
How to apply a final mask on an image?

### ISSUE THREAD

**Issue by Arsey** [MarcoForte/learning-based-matting#2]
In the repo you have exampled image and masks, but I couldn't see a code that could apply the final mask on the image. How do you apply that?

The simplest approach 
```python
image * alpha.reshape(image.shape[0], image.shape[1], 1).repeat(3, 2)` 
```
doesn't work for me as alpha matrix has really low values

**Comment by Arsey** [comment]
Ok, I was putting normalized trimap instead of trimap with values from 0 to 255 and as a result, the alpha values were small too.

**Comment by Arsey** [comment]
The question still exists for me but in the area of sharpness. How to apply the mask to have it in so pretty look?

**Comment by Arsey** [comment]
finally found  a solution https://stackoverflow.com/a/42600509/1412727

**Comment by MarcoForte** [comment]
Not sure I understand the question but if you are looking to extract the object and compose it onto a new background then you need to use the code here, https://github.com/MarcoForte/closed-form-matting, in particular https://github.com/MarcoForte/closed-form-matting/blob/master/solve_foreground_background.py
